site_name: BCOE / REDF Curriculum
site_url: https://iaa-vthitec.github.io/redf/
theme: readthedocs
nav:
  - Home: index.md
  - Approach: best_practices.md
  - Digital Literacy:
      - 'Overview':  digital_literacy.md
      - 'Curriculum Design': format.md
      - 'Agendas': lessons.md
  - Technical Skills:
      - 'Overview': technical.md
      - 'Agendas': agendas.md

extra_css: [extra.css]

